name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Homerun? We'd love to hear it.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What's the use case?
      placeholder: I want to be able to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Strategies
        - Trading
        - Dashboard / UI
        - Wallet Tracking
        - Anomaly Detection
        - API
        - Configuration
        - Documentation
        - Other
